export default [
  {
    id: 1,
    categoryId: 1,
    colorIds: [1],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль PlayStation 3',
    price: 14990,
    imagePuth: 'img/products/ps3.png',
  },
  {
    id: 2,
    categoryId: 2,
    colorIds: [1],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль PlayStation 4',
    price: 2425.99,
    imagePuth: 'img/products/ps4.png',
  },
  {
    id: 3,
    categoryId: 2,
    colorIds: [1],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль PlayStation 4 Slim',
    price: 24990,
    imagePuth: 'img/products/ps4_slim.webp',
  },
  {
    id: 4,
    categoryId: 2,
    colorIds: [1],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль PlayStation 4 Pro',
    price: 32990,
    imagePuth: 'img/products/ps4_pro.webp',
  },
  {
    id: 5,
    categoryId: 3,
    colorIds: [3],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль PlayStation 5',
    price: 44990,
    imagePuth: 'img/products/ps5.png',
  },
  {
    id: 6,
    categoryId: 1,
    colorIds: [1],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль Xbox360',
    price: 12990,
    imagePuth: 'img/products/xbox360.png',
  },
  {
    id: 7,
    categoryId: 2,
    colorIds: [1],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль Xbox One',
    price: 17990,
    imagePuth: 'img/products/xbox_one.png',
  },
  {
    id: 8,
    categoryId: 2,
    colorIds: [3],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль Xbox One S',
    price: 22990,
    imagePuth: 'img/products/xbox_one_s.png',
  },
  {
    id: 9,
    categoryId: 3,
    colorIds: [3],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль Xbox Series S',
    price: 26990,
    imagePuth: 'img/products/xbox_series_s.png',
  },
  {
    id: 10,
    categoryId: 3,
    colorIds: [1],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль Xbox Series X',
    price: 44990,
    imagePuth: 'img/products/xbox_series_x.png',
  },
  {
    id: 11,
    categoryId: 2,
    colorIds: [1, 4, 7],
    modificationColorIds: [1, 3],
    title: 'Игровая консоль Nintendo Switch',
    price: 23990,
    imagePuth: 'img/products/nintendo_switch.png',
  },
  {
    id: 12,
    categoryId: 4,
    colorIds: [7],
    modificationColorIds: [7],
    title: 'Кружка Nescafe',
    price: 1350,
    imagePuth: 'img/products/nescafe_mag.png',
  },
  {
    id: 13,
    categoryId: 5,
    colorIds: [5, 7, 9],
    modificationColorIds: [9],
    title: 'Oppo Barcelona Edition',
    price: 52990,
    imagePuth: 'img/products/oppo_barcelona_edition.png',
  },
];
